#############################################################################
# Makefile for building: BudgetApp.app/Contents/MacOS/BudgetApp
# Generated by qmake (3.1) (Qt 5.11.0)
# Project:  ../BudgetApp/BudgetApp.pro
# Template: app
# Command: /Users/matthewmagni/Qt/5.11.0/ios/bin/qmake -o BudgetApp.xcodeproj/project.pbxproj ../BudgetApp/BudgetApp.pro -spec macx-xcode CONFIG+=iphoneos CONFIG+=device CONFIG+=qml_debug
#############################################################################

MAKEFILE      = project.pbxproj

QMAKE    = /Users/matthewmagni/Qt/5.11.0/ios/bin/qmake
BudgetApp.xcodeproj/project.pbxproj: ../BudgetApp/BudgetApp.pro /Users/matthewmagni/Qt/5.11.0/ios/mkspecs/macx-ios-clang/qmake.conf /Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/spec_pre.prf \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/qdevice.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/device_config.prf \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/common/unix.conf \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/common/mac.conf \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/common/uikit.conf \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/common/ios.conf \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/common/sanitize.conf \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/common/gcc-base.conf \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/common/gcc-base-mac.conf \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/common/clang.conf \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/common/clang-mac.conf \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/common/uikit/clang.conf \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/common/uikit/qmake.conf \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/qconfig.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_3danimation.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_3danimation_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_3dcore.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_3dextras.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_3dinput.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_3dlogic.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_3dquick.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_3drender.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_3drender_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_charts.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_charts_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_core.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_core_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_datavisualization.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_edid_support_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_gamepad.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_gui.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_help.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_help_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_location.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_location_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_macextras.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_macextras_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_network.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_network_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_networkauth.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_networkauth_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_nfc.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_opengl.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_positioning.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_positioningquick.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_purchasing.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_purchasing_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_qml.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_quick.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_remoteobjects.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_repparser.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_repparser_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_script.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_script_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_scripttools.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_scxml.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_scxml_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_sensors.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_sql.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_svg.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_testlib.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_texttospeech.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_theme_support_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_uitools.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_webchannel.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_websockets.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_webview.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_webview_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_widgets.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_xml.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_zlib_private.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_darwingamepad.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_defaultgeometryloader.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_gltfgeometryloader.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_gltfsceneexport.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_gltfsceneimport.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qavfcamera.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qavfmediaplayer.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qgif.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qicns.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qico.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qios.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qiosnsphotolibrarysupport.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qjpeg.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qmacheif.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qmacjp2.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qminimal.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qmldbg_debugger.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qmldbg_inspector.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qmldbg_local.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qmldbg_messages.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qmldbg_native.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qmldbg_nativedebugger.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qmldbg_profiler.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qmldbg_server.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qmldbg_tcp.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qoffscreen.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qsqlite.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qsvg.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qsvgicon.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtaudio_coreaudio.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtexttospeech_speechios.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtga.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtgeoservices_esri.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtgeoservices_itemsoverlay.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtgeoservices_mapbox.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtgeoservices_mapboxgl.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtiff.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtposition_cl.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtsensors_ios.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtwebview_darwin.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qwbmp.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qwebp.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_scene2d.pri \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/qt_functions.prf \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/qt_config.prf \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/macx-ios-clang/qmake.conf \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/macx-xcode/qmake.conf \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/exclusive_builds.prf \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/mac/sdk.prf \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/uikit/sdk.prf \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/toolchain.prf \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/mac/toolchain.prf \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/default_pre.prf \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/mac/default_pre.prf \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/uikit/default_pre.prf \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/resolve_config.prf \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/uikit/resolve_config.prf \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/default_post.prf \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/mac/default_post.prf \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/uikit/default_post.prf \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/macx-ios-clang/features/default_post.prf \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/mac/objective_c.prf \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/qml_debug.prf \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/mac/mac.prf \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/uikit/bitcode.prf \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/warn_on.prf \
		/Users/matthewmagni/Qt/5.11.0/ios/plugins/platforms/libqios_debug.prl \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/qt.prf \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/uikit/qt.prf \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/resources.prf \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/moc.prf \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/unix/opengl.prf \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/unix/thread.prf \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/qmake_use.prf \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/file_copies.prf \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/mac/rez.prf \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/mac/asset_catalogs.prf \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/testcase_targets.prf \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/uikit/testcase_targets.prf \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/exceptions.prf \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/yacc.prf \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/lex.prf \
		../BudgetApp/BudgetApp.pro \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/macx-ios-clang/Default-568h@2x.png \
		/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/macx-ios-clang/LaunchScreen.xib \
		../BudgetApp/qml.qrc \
		/Users/matthewmagni/Qt/5.11.0/ios/lib/libQt5FontDatabaseSupport_debug.prl \
		/Users/matthewmagni/Qt/5.11.0/ios/lib/libqtfreetype_debug.prl \
		/Users/matthewmagni/Qt/5.11.0/ios/lib/libQt5GraphicsSupport_debug.prl \
		/Users/matthewmagni/Qt/5.11.0/ios/lib/libQt5ClipboardSupport_debug.prl \
		/Users/matthewmagni/Qt/5.11.0/ios/lib/libQt5Gui_debug.prl \
		/Users/matthewmagni/Qt/5.11.0/ios/lib/libqtlibpng_debug.prl \
		/Users/matthewmagni/Qt/5.11.0/ios/lib/libqtharfbuzz_debug.prl \
		/Users/matthewmagni/Qt/5.11.0/ios/lib/libQt5Core_debug.prl \
		/Users/matthewmagni/Qt/5.11.0/ios/lib/libqtpcre2_debug.prl \
		/Users/matthewmagni/Qt/5.11.0/ios/plugins/imageformats/libqgif_debug.prl \
		/Users/matthewmagni/Qt/5.11.0/ios/plugins/imageformats/libqicns_debug.prl \
		/Users/matthewmagni/Qt/5.11.0/ios/plugins/imageformats/libqico_debug.prl \
		/Users/matthewmagni/Qt/5.11.0/ios/plugins/imageformats/libqjpeg_debug.prl \
		/Users/matthewmagni/Qt/5.11.0/ios/plugins/imageformats/libqmacheif_debug.prl \
		/Users/matthewmagni/Qt/5.11.0/ios/plugins/imageformats/libqmacjp2_debug.prl \
		/Users/matthewmagni/Qt/5.11.0/ios/plugins/imageformats/libqtga_debug.prl \
		/Users/matthewmagni/Qt/5.11.0/ios/plugins/imageformats/libqtiff_debug.prl \
		/Users/matthewmagni/Qt/5.11.0/ios/plugins/imageformats/libqwbmp_debug.prl \
		/Users/matthewmagni/Qt/5.11.0/ios/plugins/imageformats/libqwebp_debug.prl \
		/Users/matthewmagni/Qt/5.11.0/ios/plugins/qmltooling/libqmldbg_debugger_debug.prl \
		/Users/matthewmagni/Qt/5.11.0/ios/plugins/qmltooling/libqmldbg_inspector_debug.prl \
		/Users/matthewmagni/Qt/5.11.0/ios/plugins/qmltooling/libqmldbg_local_debug.prl \
		/Users/matthewmagni/Qt/5.11.0/ios/plugins/qmltooling/libqmldbg_messages_debug.prl \
		/Users/matthewmagni/Qt/5.11.0/ios/plugins/qmltooling/libqmldbg_native_debug.prl \
		/Users/matthewmagni/Qt/5.11.0/ios/plugins/qmltooling/libqmldbg_nativedebugger_debug.prl \
		/Users/matthewmagni/Qt/5.11.0/ios/plugins/qmltooling/libqmldbg_profiler_debug.prl \
		/Users/matthewmagni/Qt/5.11.0/ios/plugins/qmltooling/libqmldbg_quickprofiler_debug.prl \
		/Users/matthewmagni/Qt/5.11.0/ios/plugins/qmltooling/libqmldbg_server_debug.prl \
		/Users/matthewmagni/Qt/5.11.0/ios/plugins/qmltooling/libqmldbg_tcp_debug.prl \
		/Users/matthewmagni/Qt/5.11.0/ios/plugins/bearer/libqgenericbearer_debug.prl \
		/Users/matthewmagni/Qt/5.11.0/ios/lib/libQt5Quick_debug.prl \
		/Users/matthewmagni/Qt/5.11.0/ios/lib/libQt5Qml_debug.prl \
		/Users/matthewmagni/Qt/5.11.0/ios/lib/libQt5Network_debug.prl \
		/Users/matthewmagni/Qt/5.11.0/ios/qml/QtQuick.2/libqtquick2plugin_debug.prl \
		/Users/matthewmagni/Qt/5.11.0/ios/qml/QtQuick/Window.2/libwindowplugin_debug.prl
	$(QMAKE) -o BudgetApp.xcodeproj/project.pbxproj ../BudgetApp/BudgetApp.pro -spec macx-xcode CONFIG+=iphoneos CONFIG+=device CONFIG+=qml_debug
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/spec_pre.prf:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/qdevice.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/device_config.prf:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/common/unix.conf:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/common/mac.conf:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/common/uikit.conf:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/common/ios.conf:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/common/sanitize.conf:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/common/gcc-base.conf:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/common/gcc-base-mac.conf:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/common/clang.conf:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/common/clang-mac.conf:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/common/uikit/clang.conf:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/common/uikit/qmake.conf:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/qconfig.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_3danimation.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_3danimation_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_3dcore.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_3dcore_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_3dextras.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_3dextras_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_3dinput.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_3dinput_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_3dlogic.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_3dlogic_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_3dquick.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_3dquick_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_3dquickanimation.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_3dquickextras.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_3dquickinput.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_3dquickrender.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_3drender.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_3drender_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_bluetooth.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_charts.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_charts_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_concurrent.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_concurrent_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_core.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_core_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_datavisualization.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_datavisualization_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_edid_support_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_fb_support_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_gamepad.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_gamepad_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_graphics_support_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_gui.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_gui_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_help.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_help_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_location.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_location_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_macextras.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_macextras_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_multimedia.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_multimedia_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_network.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_network_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_networkauth.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_networkauth_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_nfc.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_nfc_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_opengl.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_opengl_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_openglextensions.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_positioning.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_positioning_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_positioningquick.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_positioningquick_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_printsupport.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_printsupport_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_purchasing.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_purchasing_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_qml.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_qml_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_qmldebug_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_qmltest.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_qmltest_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_quick.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_quick_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_quickcontrols2.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_quickwidgets.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_remoteobjects.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_repparser.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_repparser_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_script.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_script_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_scripttools.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_scripttools_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_scxml.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_scxml_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_sensors.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_sensors_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_sql.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_sql_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_svg.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_svg_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_testlib.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_testlib_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_texttospeech.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_texttospeech_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_theme_support_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_uiplugin.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_uitools.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_uitools_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_webchannel.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_webchannel_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_websockets.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_websockets_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_webview.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_webview_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_widgets.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_widgets_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_xml.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_xml_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_lib_zlib_private.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_darwingamepad.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_defaultgeometryloader.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_gltfgeometryloader.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_gltfsceneexport.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_gltfsceneimport.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qavfcamera.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qavfmediaplayer.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qgenericbearer.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qgif.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qicns.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qico.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qios.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qiosnsphotolibrarysupport.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qjpeg.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qmacheif.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qmacjp2.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qminimal.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qmldbg_debugger.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qmldbg_inspector.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qmldbg_local.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qmldbg_messages.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qmldbg_native.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qmldbg_nativedebugger.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qmldbg_profiler.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qmldbg_server.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qmldbg_tcp.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qoffscreen.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qsqlite.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qsvg.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qsvgicon.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtaudio_coreaudio.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtexttospeech_speechios.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtga.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtgeoservices_esri.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtgeoservices_itemsoverlay.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtgeoservices_mapbox.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtgeoservices_mapboxgl.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtiff.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtposition_cl.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtsensors_generic.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtsensors_ios.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qtwebview_darwin.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qwbmp.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_qwebp.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/modules/qt_plugin_scene2d.pri:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/qt_functions.prf:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/qt_config.prf:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/macx-ios-clang/qmake.conf:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/macx-xcode/qmake.conf:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/spec_post.prf:
.qmake.stash:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/exclusive_builds.prf:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/mac/sdk.prf:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/uikit/sdk.prf:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/toolchain.prf:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/mac/toolchain.prf:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/default_pre.prf:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/mac/default_pre.prf:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/uikit/default_pre.prf:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/resolve_config.prf:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/uikit/resolve_config.prf:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/default_post.prf:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/mac/default_post.prf:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/uikit/default_post.prf:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/macx-ios-clang/features/default_post.prf:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/mac/objective_c.prf:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/qml_debug.prf:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/mac/mac.prf:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/uikit/bitcode.prf:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/warn_on.prf:
/Users/matthewmagni/Qt/5.11.0/ios/plugins/platforms/libqios_debug.prl:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/qt.prf:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/uikit/qt.prf:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/resources.prf:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/moc.prf:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/unix/opengl.prf:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/unix/thread.prf:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/qmake_use.prf:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/file_copies.prf:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/mac/rez.prf:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/mac/asset_catalogs.prf:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/testcase_targets.prf:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/uikit/testcase_targets.prf:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/exceptions.prf:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/yacc.prf:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/features/lex.prf:
../BudgetApp/BudgetApp.pro:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/macx-ios-clang/Default-568h@2x.png:
/Users/matthewmagni/Qt/5.11.0/ios/mkspecs/macx-ios-clang/LaunchScreen.xib:
../BudgetApp/qml.qrc:
/Users/matthewmagni/Qt/5.11.0/ios/lib/libQt5FontDatabaseSupport_debug.prl:
/Users/matthewmagni/Qt/5.11.0/ios/lib/libqtfreetype_debug.prl:
/Users/matthewmagni/Qt/5.11.0/ios/lib/libQt5GraphicsSupport_debug.prl:
/Users/matthewmagni/Qt/5.11.0/ios/lib/libQt5ClipboardSupport_debug.prl:
/Users/matthewmagni/Qt/5.11.0/ios/lib/libQt5Gui_debug.prl:
/Users/matthewmagni/Qt/5.11.0/ios/lib/libqtlibpng_debug.prl:
/Users/matthewmagni/Qt/5.11.0/ios/lib/libqtharfbuzz_debug.prl:
/Users/matthewmagni/Qt/5.11.0/ios/lib/libQt5Core_debug.prl:
/Users/matthewmagni/Qt/5.11.0/ios/lib/libqtpcre2_debug.prl:
/Users/matthewmagni/Qt/5.11.0/ios/plugins/imageformats/libqgif_debug.prl:
/Users/matthewmagni/Qt/5.11.0/ios/plugins/imageformats/libqicns_debug.prl:
/Users/matthewmagni/Qt/5.11.0/ios/plugins/imageformats/libqico_debug.prl:
/Users/matthewmagni/Qt/5.11.0/ios/plugins/imageformats/libqjpeg_debug.prl:
/Users/matthewmagni/Qt/5.11.0/ios/plugins/imageformats/libqmacheif_debug.prl:
/Users/matthewmagni/Qt/5.11.0/ios/plugins/imageformats/libqmacjp2_debug.prl:
/Users/matthewmagni/Qt/5.11.0/ios/plugins/imageformats/libqtga_debug.prl:
/Users/matthewmagni/Qt/5.11.0/ios/plugins/imageformats/libqtiff_debug.prl:
/Users/matthewmagni/Qt/5.11.0/ios/plugins/imageformats/libqwbmp_debug.prl:
/Users/matthewmagni/Qt/5.11.0/ios/plugins/imageformats/libqwebp_debug.prl:
/Users/matthewmagni/Qt/5.11.0/ios/plugins/qmltooling/libqmldbg_debugger_debug.prl:
/Users/matthewmagni/Qt/5.11.0/ios/plugins/qmltooling/libqmldbg_inspector_debug.prl:
/Users/matthewmagni/Qt/5.11.0/ios/plugins/qmltooling/libqmldbg_local_debug.prl:
/Users/matthewmagni/Qt/5.11.0/ios/plugins/qmltooling/libqmldbg_messages_debug.prl:
/Users/matthewmagni/Qt/5.11.0/ios/plugins/qmltooling/libqmldbg_native_debug.prl:
/Users/matthewmagni/Qt/5.11.0/ios/plugins/qmltooling/libqmldbg_nativedebugger_debug.prl:
/Users/matthewmagni/Qt/5.11.0/ios/plugins/qmltooling/libqmldbg_profiler_debug.prl:
/Users/matthewmagni/Qt/5.11.0/ios/plugins/qmltooling/libqmldbg_quickprofiler_debug.prl:
/Users/matthewmagni/Qt/5.11.0/ios/plugins/qmltooling/libqmldbg_server_debug.prl:
/Users/matthewmagni/Qt/5.11.0/ios/plugins/qmltooling/libqmldbg_tcp_debug.prl:
/Users/matthewmagni/Qt/5.11.0/ios/plugins/bearer/libqgenericbearer_debug.prl:
/Users/matthewmagni/Qt/5.11.0/ios/lib/libQt5Quick_debug.prl:
/Users/matthewmagni/Qt/5.11.0/ios/lib/libQt5Qml_debug.prl:
/Users/matthewmagni/Qt/5.11.0/ios/lib/libQt5Network_debug.prl:
/Users/matthewmagni/Qt/5.11.0/ios/qml/QtQuick.2/libqtquick2plugin_debug.prl:
/Users/matthewmagni/Qt/5.11.0/ios/qml/QtQuick/Window.2/libwindowplugin_debug.prl:
qmake: FORCE
	@$(QMAKE) -o BudgetApp.xcodeproj/project.pbxproj ../BudgetApp/BudgetApp.pro -spec macx-xcode CONFIG+=iphoneos CONFIG+=device CONFIG+=qml_debug

qmake_all: FORCE

